### ISSUE TITLE
Error: Cannot find module 'recastai'

### ISSUE THREAD

**Issue by ChowYoung** [RecastAI/SDK-NodeJS#17]
when i run the demo  and i have install recastai。

`node index.js`

```
//index.js
var recastai = require('recast');
const client = new recastai.request('YOUR_REQUEST_TOKEN', 'en');

client.analyseText('hello')
	.then(function (res) {
		if (res.intent()) {
			console.log('Intent: ', res.intent().slug)
		}
		if (res.intent().slug === 'YOUR_EXPECTED_INTENT') {
			// Do your code...
		}
	});
```
show：
```
Error: Cannot find module 'recastai'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Young/cool/recastai/index.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
please help me ,tks！

**Comment by mandre42** [comment]
Hello !

Just try to replace
`var recastai = require('recast');ˋ
with
ˋvar recastai = require('recastai');`

**Comment by ChowYoung** [comment]
oops! it's my fault.and i have use the `var recastai = require('recastai');` 

```
//index.js
var recastai = require('recastai');
const client = new recastai.request('YOUR_REQUEST_TOKEN', 'en');

client.analyseText('hello')
	.then(function (res) {
		if (res.intent()) {
			console.log('Intent: ', res.intent().slug)
		}
		if (res.intent().slug === 'YOUR_EXPECTED_INTENT') {
			// Do your code...
		}
	});

```
but also show those：
```
Error: Cannot find module 'recastai'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Young/cool/recastai/index.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by mandre42** [comment]
I just fix this issue (npm package issue)

Run `npm update`, it should work now !
If not, run `npm install recastai --save`

Thanks for your feedback
